<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0">
<context>
    <name>@default</name>
    <message>
        <location filename="../../qgis_plugin_tools/tools/custom_logging.py" line="63"/>
        <source>Due to memory limitations on this machine, the plugin {} can not handle the full log</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="54"/>
        <source>Install Lizsync tools on the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="57"/>
        <source>01 Installation</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="97"/>
        <source>PostgreSQL connection to the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="105"/>
        <source>Drop audit schema and all data ?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="113"/>
        <source>Drop lizsync schema and all data ?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="184"/>
        <source>Output status</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="189"/>
        <source>Output message</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="137"/>
        <source>You must use the &quot;Configure Lizsync plugin&quot; alg to set the central database connection name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="143"/>
        <source>The configured connection name does not exists in QGIS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="185"/>
        <source>Schema does not exists. Continue</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="191"/>
        <source>Schema already exists in database ! If you REALLY want to drop and recreate it (and loose all data), check the *Overwrite* checkbox</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="214"/>
        <source>Trying to drop schema</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="226"/>
        <source>* Schema has been droped</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="267"/>
        <source>SQL file successfully played</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="288"/>
        <source>Version added in the lizsync metadata table</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="295"/>
        <source>Lizsync database structure has been successfully created.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="60"/>
        <source>Prepare the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="112"/>
        <source>Add server id in metadata table</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="120"/>
        <source>Add unique identifiers in all tables</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="128"/>
        <source>Add audit triggers in all tables</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="136"/>
        <source>Restrict to comma separated schema names. NB: schemas public, lizsync &amp; audit are never processed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="248"/>
        <source>You must use the &quot;Configure Lizsync plugin&quot; alg to set the CENTRAL database connection name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="169"/>
        <source>Schema lizsync does not exist in database !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="227"/>
        <source>Everything is OK. No action needed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="242"/>
        <source>CHECK LIZSYNC STRUCTURE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="244"/>
        <source>Lizsync has not been installed in the central database. Run the script &quot;Create database structure&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="250"/>
        <source>Lizsync structure OK</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="254"/>
        <source>ADD SERVER ID IN THE METADATA TABLE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="271"/>
        <source>Server id successfully added</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="273"/>
        <source>Error adding server name in server_metadata table.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="280"/>
        <source>ADD UID COLUMNS IN ALL THE TABLES OF THE SPECIFIED SCHEMAS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="305"/>
        <source>UID columns have been successfully added in the following tables:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="311"/>
        <source>No UID columns were missing.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="320"/>
        <source>ADD AUDIT TRIGGERS IN ALL THE TABLES OF THE GIVEN SCHEMAS</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="351"/>
        <source>Audit triggers have been successfully added in the following tables:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="357"/>
        <source>No audit triggers were missing.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="57"/>
        <source>Deploy a database package to the clone</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="62"/>
        <source>02 Package and deploy database data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="106"/>
        <source>PostgreSQL connection to the clone database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="109"/>
        <source>PostgreSQL binary path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="164"/>
        <source>Database ZIP archive path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="243"/>
        <source>The needed PostgreSQL binaries cannot be found in the specified path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="196"/>
        <source>The ZIP archive does not exists in the specified path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="218"/>
        <source>Package not found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="217"/>
        <source>No internet connection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="229"/>
        <source>UNCOMPRESS PACKAGE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="235"/>
        <source>Package uncompressed successfully</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="237"/>
        <source>Package extraction error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="258"/>
        <source>GET EXISTING METADATA TO AVOID RECREATING SERVER_ID FOR THIS CLONE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="275"/>
        <source>Clone database already has sync metadata table</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="295"/>
        <source>Clone metadata are already set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="468"/>
        <source>* server id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="469"/>
        <source>* server name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="349"/>
        <source>GET THE LIST OF SYNCHRONIZED SCHEMAS FROM THE FILE sync_schemas.txt</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="355"/>
        <source>No schema to syncronize</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="358"/>
        <source>Schema list found in sync_schemas.txt</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="362"/>
        <source>RUN SQL SCRIPT FROM THE DECOMPRESSED ZIP FILE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="368"/>
        <source>SQL files not found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="578"/>
        <source>Error getting database connection information</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="409"/>
        <source>Loading file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="433"/>
        <source>Error loading file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="441"/>
        <source>ADDING THE SERVER ID IN THE CLONE metadata table</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="467"/>
        <source>Server metadata added in the clone database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="471"/>
        <source>Error while adding server id in clone metadata table</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="478"/>
        <source>ADDING THE LIST OF SYNCHRONIZED SCHEMAS FOR THIS CLONE IN THE CENTRAL DATABASE </source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="496"/>
        <source>List of synchronized schemas added in central database for this clone</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="499"/>
        <source>Error while adding the synchronized schemas in the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="504"/>
        <source>ADD CLONE ID IN THE CENTRAL DATABASE HISTORY ITEM FOR THIS ARCHIVE DEPLOYEMENT</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="523"/>
        <source>History item has been successfully updated for this archive deployement in the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="526"/>
        <source>Error while updating the history item for this archive deployement</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="531"/>
        <source>The central database ZIP package has been successfully deployed to the clone</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="53"/>
        <source>Two-way database synchronization between central and clone databases</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="70"/>
        <source>03 Synchronize data and files</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="148"/>
        <source>Internet connection OK</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="188"/>
        <source>Server id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="206"/>
        <source>Clone id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="452"/>
        <source>Number of features to synchronize</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="361"/>
        <source>SQL queries have been replayed from the central to the clone database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="387"/>
        <source>Logged actions sync_data has been updated in the central database with the clone id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="408"/>
        <source>History sync_status has been updated to &quot;done&quot; in the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="414"/>
        <source>No data to synchronize from the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="487"/>
        <source>New history item has been created in the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="554"/>
        <source>Two-way database synchronization done</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="65"/>
        <source>Synchronize the clone media subfolder to the central FTP server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="107"/>
        <source>Local QGIS project folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="126"/>
        <source>Central FTP Server host</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="135"/>
        <source>Central FTP Server port</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="144"/>
        <source>Central FTP Server login</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="153"/>
        <source>Central FTP Server remote directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="188"/>
        <source>Check internet connection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="240"/>
        <source>Could not retrieve password from ~/.netrc file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="243"/>
        <source>Could not retrieve password from ~/.netrc file or is empty</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="255"/>
        <source>CHECK LOCAL PROJECT DIRECTORY</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="257"/>
        <source>QGIS project local directory not found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="260"/>
        <source>QGIS project local directory ok</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="263"/>
        <source>CHECK REMOTE DIRECTORY</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="270"/>
        <source>Remote directory exists in the central server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="273"/>
        <source>Remote directory does not exist</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="249"/>
        <source>START FTP DIRECTORY SYNCHRONIZATION TO SERVER</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="295"/>
        <source>Local directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="253"/>
        <source>FTP remote directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="262"/>
        <source>Local directory does not exists. No synchronization needed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="267"/>
        <source>Media upload subfolder sucessfully synchronized to the central server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="59"/>
        <source>Create a package from the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="122"/>
        <source>List of schemas to package, separated by commas. (schemas public, lizsync &amp; audit are never processed)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="173"/>
        <source>Output archive file (ZIP)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="206"/>
        <source>CHECK IF LIZSYNC HAS BEEN INSTALLED AND DATABASE INITIALIZED</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="213"/>
        <source>Some needed configuration are missing in the central database. Please correct them before proceeding.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="224"/>
        <source>Every test has passed successfully !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="304"/>
        <source>CREATE SCRIPT 01_before.sql</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="338"/>
        <source>File 01_before.sql created</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="342"/>
        <source>CREATE SCRIPT 02_data.sql</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="359"/>
        <source>CREATE SCRIPT 03_after.sql</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="384"/>
        <source>File 03_after.sql created</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="389"/>
        <source>CREATE SCRIPT 04_lizsync.sql</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="407"/>
        <source>ADD SCHEMAS TO FILE sync_schemas.txt</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="416"/>
        <source>File sync_schemas.txt created</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="423"/>
        <source>ADD NEW SYNC HISTORY ITEM IN CENTRAL DATABASE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="451"/>
        <source>New synchronization history item has been added in the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="456"/>
        <source>File sync_id.txt created</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="465"/>
        <source>No synchronization item could be added !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="499"/>
        <source>Error while zipping file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="502"/>
        <source>Package has been successfully created !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/send_projects_and_files_to_clone_ftp.py" line="68"/>
        <source>Send local QGIS projects and files to the clone FTP server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="112"/>
        <source>PostgreSQL connection to the local database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="196"/>
        <source>Local desktop QGIS project folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="416"/>
        <source>Clone FTP Server host</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="233"/>
        <source>Clone FTP Server port</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="425"/>
        <source>Clone FTP Server login</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="428"/>
        <source>Clone FTP Server remote directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="162"/>
        <source>List of sub-directory to exclude from synchro, separated by commas.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="215"/>
        <source>CHECK INTERNET CONNECTION</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="296"/>
        <source>FTP directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/send_projects_and_files_to_clone_ftp.py" line="302"/>
        <source>Synchronization successfull</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="82"/>
        <source>Cannot connect to database with</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="90"/>
        <source>Unable to get database from connection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="166"/>
        <source>Cannot connect to database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="196"/>
        <source>Unknown error occured while fetching data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="272"/>
        <source>Lizsync structure has been installed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="284"/>
        <source>The table lizsync.metadata has not been found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="295"/>
        <source>Server id is not empty</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="304"/>
        <source>The server id in lizsync.metadata is not set</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="315"/>
        <source>No missing uid columns</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="340"/>
        <source>Some tables do not have the required uid column</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="349"/>
        <source>No missing audit triggers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="374"/>
        <source>Some tables are not monitored by the audit trigger tool</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="419"/>
        <source>No FTP binary has been found in your system</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="420"/>
        <source>FTP Binary has been found in your system</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="549"/>
        <source>Error during FTP sync</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="552"/>
        <source>FTP sync done</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="572"/>
        <source>PostgreSQL pg_dump tool cannot be found in specified path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="629"/>
        <source>Database has been successfull dumped</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="632"/>
        <source>Error dumping database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="695"/>
        <source>Process QGIS project file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="731"/>
        <source>Overwrite QGIS project file with new data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="77"/>
        <source>Configure Lizsync plugin</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="391"/>
        <source>WinSCP binary path (Windows only)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="134"/>
        <source>PostgreSQL connection to the CENTRAL database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="406"/>
        <source>Central FTP Server password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="208"/>
        <source>PostgreSQL connection to the CLONE database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="251"/>
        <source>Clone FTP Server password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="172"/>
        <source>Clone QGIS project folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="440"/>
        <source>Database ZIP archive default path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="389"/>
        <source>PostgreSQL local binary path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="394"/>
        <source>PostgreSQL connection to central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="413"/>
        <source>PostgreSQL connection to local clone database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="419"/>
        <source>clone FTP Server port</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="431"/>
        <source>Local Desktop QGIS project folder</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="447"/>
        <source>Configuration has been saved</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="54"/>
        <source>Upgrade LizSync tools in the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="99"/>
        <source>Check this box to upgrade. No action will be done otherwise</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="195"/>
        <source>You must check the box to run the upgrade !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="216"/>
        <source>No installed version found in the database !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="219"/>
        <source>Database structure version</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="227"/>
        <source>Plugin version</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="233"/>
        <source>The database version already matches the plugin version. No upgrade needed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="293"/>
        <source>Lizsync database structure has been successfully upgraded.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="67"/>
        <source>Get projects and files from the central FTP server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="76"/>
        <source> Get QGIS projects and files from the give FTP server and remote directory and adapt QGIS projects for the local clone database by replacing PostgreSQL connection data with the local PostgreSQL server data. An internet connection is needed to use this algorithm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="286"/>
        <source>USELAND CONTEXT: Remove old QGIS project files to avoid bug</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="309"/>
        <source>ADAPT QGIS PROJECTS FOR OFFLINE USE</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="316"/>
        <source>QGIS projects and file successfully synchronized from the central FTP server</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/provider.py" line="67"/>
        <source>Lizsync</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../test/test_translations.py" line="48"/>
        <source>Good morning</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="69"/>
        <source> Prepare the central server PostgreSQL database with the needed data for LizSync tool.

 LizSync needs to have :
 * A server ID stored in the lizsync.server_metadata table
 * All tables from the given schema must have a unique identifier column (uid) with standard uuid inside
 * All tables from the given schema must be audited (trigger of the audit tool)

 You can pass a list of PostgreSQL central database schemas and this alg will add the necessary data and tools</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="62"/>
        <source> This scripts run a two-way data synchronization between the central and clone database.

 The data to synchronize are listed by reading the content of the &quot;audit.logged_actions&quot; of each database, since the last synchronization or the last deployement of ZIP package.

 This audit data are transformed into INSERT/UPDATE/DELETE SQL queries which are played in the databases in this order:
 1/ From the CENTRAL to the CLONE database
 2/ From the CLONE to the CENTRAL database

The central database stores which clone has replayed which audited modification, and keeps an history of synchronization items.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="74"/>
        <source> Send media files, such as new images, stored in the clone QGIS &quot;media/upload/&quot; folder, TO the central FTP server remote directory &quot;media/upload/&quot;

 These media files can for example have been added by using Lizmap editing form.

 Every file existing in the clone &quot;media/upload/&quot; folder but not in the central server &quot;media/upload/&quot; folder will be sent.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="68"/>
        <source> Package data from the central database, for future deployement on one or several clone(s).

 This script backups all data from the given list of schemas to a ZIP archive, named by default &quot;central_database_package.zip&quot;.

 An internet connection is needed because a synchronization item must be written to the central database &quot;lizsync.history&quot; table during the process. and obviously data must be downloaded from the central database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/send_projects_and_files_to_clone_ftp.py" line="77"/>
        <source> Send QGIS projects and files to the clone FTP server remote directory.

 This script can be used by the geomatician in charge of the deployment of data to one or several clone(s).

 It synchronizes the files from the given local QGIS project folder to the clone remote folder by using the given FTP connexion. This means all the files from the clone folder will be overwritten by the files from the local QGIS project folder.

 Beware ! This script does not adapt projects for the clone database (no modification of the PostgreSQL connexion data inside the QGIS project files) !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="63"/>
        <source> Upgrade the Lizsync tables and functions in the central database.

 If you have upgraded your QGIS LizSync plugin, you can run this script to upgrade your central database to the new plugin version.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="241"/>
        <source>CHECK UNCOMPRESSED FILES</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="252"/>
        <source>One mandatory file has not been found in the ZIP archive</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="254"/>
        <source>All the mandatory files have been sucessfully found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="307"/>
        <source>CHECK LAST SYNCHRONIZATION</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="311"/>
        <source>No synchronization ID has been found in the file sync_id.txt</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="344"/>
        <source>Synchronization has already been made on this clone since the deployment of this package. Abort the current deployment</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="63"/>
        <source> Install the LizSync schema with tables and function on the central database.

 This script will add
 * An audit schema with auditing functions and tables
 * A lizsync schema with tables and functions

Beware ! If you check the &quot;override&quot; checkboxes, you will loose all existing data in the audit and/or lizsync schema !</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="66"/>
        <source> Deploy a ZIP archive, previously saved with the &quot;Package central database&quot; algorithm, to the chosen clone. This ZIP archive, named by default &quot;central_database_package.zip&quot; contains data from the central PostgreSQL database.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="86"/>
        <source> Configure the LizSync plugin

 You must run this script before any other script.
 Every parameter will be used in the other algorithms, as default values for parameters.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="545"/>
        <source>No data to synchronize from the clone database</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="443"/>
        <source>Excluded columns: list of columns that will never be synchronized</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="437"/>
        <source>Additionnal SQL file to run in the clone after the ZIP deployement</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
