<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="2.0" language="fr" sourcelanguage="">
<context>
    <name>@default</name>
    <message>
        <location filename="../../qgis_plugin_tools/tools/custom_logging.py" line="63"/>
        <source>Due to memory limitations on this machine, the plugin {} can not handle the full log</source>
        <translation>Cette extension {} ne peut pas gérer le log complet à cause d&apos;une limitation de mémoire</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="54"/>
        <source>Install Lizsync tools on the central database</source>
        <translation>Installer les outils LizSync sur la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="57"/>
        <source>01 Installation</source>
        <translation>01 Installation</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="97"/>
        <source>PostgreSQL connection to the central database</source>
        <translation>Connexion PostgreSQL à la base de données centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="105"/>
        <source>Drop audit schema and all data ?</source>
        <translation>Supprimer le schéma audit et toutes ses données ?</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="113"/>
        <source>Drop lizsync schema and all data ?</source>
        <translation>Supprimer le schéma lizsync et toutes ses données ?</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="184"/>
        <source>Output status</source>
        <translation>Statut de la sortie</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="189"/>
        <source>Output message</source>
        <translation>Message de sortie</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="137"/>
        <source>You must use the &quot;Configure Lizsync plugin&quot; alg to set the central database connection name</source>
        <translation>Vous devez utiliser l&apos;algorithme &quot;Configurer le plugin Lizsync&quot; pour définir le nom de la connexion à la base de données centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="143"/>
        <source>The configured connection name does not exists in QGIS</source>
        <translation>Le nom de connexion défini n&apos;existe pas dans QGIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="185"/>
        <source>Schema does not exists. Continue</source>
        <translation>Le schéma n&apos;existe pas. Continuer</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="191"/>
        <source>Schema already exists in database ! If you REALLY want to drop and recreate it (and loose all data), check the *Overwrite* checkbox</source>
        <translation>Le schéma existe déjà dans la base de données ! Si vous voulez VRAIMENT supprimer et recréer le schéma (et perdre les données), cocher la case &quot;Écraser&quot;</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="214"/>
        <source>Trying to drop schema</source>
        <translation>Essai de suppression du schéma</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="226"/>
        <source>* Schema has been droped</source>
        <translation>* Le schéma a été supprimé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="267"/>
        <source>SQL file successfully played</source>
        <translation>Le fichier SQL a été bien exécuté</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="288"/>
        <source>Version added in the lizsync metadata table</source>
        <translation>Version ajoutée dans la table de métadonnées lizsync</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="295"/>
        <source>Lizsync database structure has been successfully created.</source>
        <translation>La structure de la base de données a bien été créée.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="60"/>
        <source>Prepare the central database</source>
        <translation>Préparer la base de données centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="112"/>
        <source>Add server id in metadata table</source>
        <translation>Ajouter l&apos;ID du serveur dans la table de métadonnées</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="120"/>
        <source>Add unique identifiers in all tables</source>
        <translation>Ajouter un champ d&apos;identifiant unique dans toutes les tables</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="128"/>
        <source>Add audit triggers in all tables</source>
        <translation>Ajouter les triggers d&apos;audit</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="136"/>
        <source>Restrict to comma separated schema names. NB: schemas public, lizsync &amp; audit are never processed</source>
        <translation>Restreindre aux noms de schémas séparés par virgule. NB: les schémas public, lizsync &amp; audit ne sont jamais traités</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="212"/>
        <source>You must use the &quot;Configure Lizsync plugin&quot; alg to set the CENTRAL database connection name</source>
        <translation>Vous devez utiliser l&apos;algorithme &quot;Configurer le plugin LizSync&quot; pour définir le nom de la connexion à la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="169"/>
        <source>Schema lizsync does not exist in database !</source>
        <translation>Le schéma lizsync n&apos;existe pas dans la base de données !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="227"/>
        <source>Everything is OK. No action needed</source>
        <translation>Tout est OK. Pas d&apos;action requise</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="242"/>
        <source>CHECK LIZSYNC STRUCTURE</source>
        <translation>VÉRIFICATION DE LA STRUCTURE LIZSYNC</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="244"/>
        <source>Lizsync has not been installed in the central database. Run the script &quot;Create database structure&quot;</source>
        <translation>Lizsync n&apos;a pas été installé sur la base centrale. Lancer l&apos;algorithme &quot;Installer les outils Lizsync sur la base de données centrale&quot;</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="250"/>
        <source>Lizsync structure OK</source>
        <translation>Structure Lizsync OK</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="254"/>
        <source>ADD SERVER ID IN THE METADATA TABLE</source>
        <translation>AJOUT DE L&apos;IDENTIFIANT DU SERVEUR DANS LA TABLE DE MÉTADONNÉES</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="271"/>
        <source>Server id successfully added</source>
        <translation>Identifiant du serveur bien ajouté</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="273"/>
        <source>Error adding server name in server_metadata table.</source>
        <translation>Erreur lors de l&apos;ajout du nom du serveur dans la table server_metadata</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="280"/>
        <source>ADD UID COLUMNS IN ALL THE TABLES OF THE SPECIFIED SCHEMAS</source>
        <translation>AJOUT DU CHAMP D&apos;IDENTIFIANT UNIQUE DANS TOUTES LES TABLES DES SCHÉMAS CHOISIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="305"/>
        <source>UID columns have been successfully added in the following tables:</source>
        <translation>Les champs UID ont bien été ajoutés dans les tables suivantes :</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="311"/>
        <source>No UID columns were missing.</source>
        <translation>Aucun champ UID n&apos;était manquant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="320"/>
        <source>ADD AUDIT TRIGGERS IN ALL THE TABLES OF THE GIVEN SCHEMAS</source>
        <translation>AJOUT DES TRIGGERS D&apos;AUDIT DANS TOUTES LES TABLES DES SCHÉMAS CHOISIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="351"/>
        <source>Audit triggers have been successfully added in the following tables:</source>
        <translation>Les triggers d&apos;audit ont bien été ajoutés dans les tables suivantes :</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="357"/>
        <source>No audit triggers were missing.</source>
        <translation>Aucun trigger d&apos;audit n&apos;était manquant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="57"/>
        <source>Deploy a database package to the clone</source>
        <translation>Charger l&apos;archive vers le clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="61"/>
        <source>02 Package and deploy database data</source>
        <translation>02 Récupérer et charger une archive de la base de données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="106"/>
        <source>PostgreSQL connection to the clone database</source>
        <translation>Connexion PostgreSQL vers la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="107"/>
        <source>PostgreSQL binary path</source>
        <translation>Chemins binaires de PostgreSQL</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="134"/>
        <source>Database ZIP archive path</source>
        <translation>Chemin vers l&apos;archive ZIP de base de données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="207"/>
        <source>The needed PostgreSQL binaries cannot be found in the specified path</source>
        <translation>Les exécutables de PostgreSQL n&apos;ont pas été trouvés dans le chemin spécifié</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="185"/>
        <source>The ZIP archive does not exists in the specified path</source>
        <translation>L&apos;archive ZIP n&apos;existe pas dans le chemin spécifié</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="207"/>
        <source>Package not found</source>
        <translation>L&apos;archive n&apos;a pas été trouvée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="217"/>
        <source>No internet connection</source>
        <translation>Aucune connexion internet</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="218"/>
        <source>UNCOMPRESS PACKAGE</source>
        <translation>DÉCOMPRESSION DE L&apos;ARCHIVE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="224"/>
        <source>Package uncompressed successfully</source>
        <translation>L&apos;archive a bien été décompressée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="226"/>
        <source>Package extraction error</source>
        <translation>Erreur d&apos;extraction de l&apos;archive</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="247"/>
        <source>GET EXISTING METADATA TO AVOID RECREATING SERVER_ID FOR THIS CLONE</source>
        <translation>RÉCUPÉRATION DES MÉTADONNÉES POUR NE PAS RECRÉER DE SERVER_ID POUR CE CLONE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="264"/>
        <source>Clone database already has sync metadata table</source>
        <translation>La base de données clone a déjà une table de métadonnées</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="284"/>
        <source>Clone metadata are already set</source>
        <translation>Les métadonnées du clone sont déjà définies</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="448"/>
        <source>* server id</source>
        <translation>* id du serveur</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="449"/>
        <source>* server name</source>
        <translation>* nom du serveur</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="338"/>
        <source>GET THE LIST OF SYNCHRONIZED SCHEMAS FROM THE FILE sync_schemas.txt</source>
        <translation>RÉCUPÉRATION DE LA LISTE DES SCHÉMAS DEPUIS LE FICHIER sync_schemas.txt</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="344"/>
        <source>No schema to syncronize</source>
        <translation>Aucun schéma à synchroniser</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="347"/>
        <source>Schema list found in sync_schemas.txt</source>
        <translation>Liste de schémas trouvée dans sync_schemas.txt</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="351"/>
        <source>RUN SQL SCRIPT FROM THE DECOMPRESSED ZIP FILE</source>
        <translation>LANCEMENT DU SCRIPT SQL DEPUIS L&apos;ARCHIVE DÉCOMPRESSÉE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="357"/>
        <source>SQL files not found</source>
        <translation>Fichier SQL non trouvé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="578"/>
        <source>Error getting database connection information</source>
        <translation>Erreur de récupération des informations de connexion à la base de données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="389"/>
        <source>Loading file</source>
        <translation>Chargement du fichier</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="413"/>
        <source>Error loading file</source>
        <translation>Erreur de chargement du fichier</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="421"/>
        <source>ADDING THE SERVER ID IN THE CLONE metadata table</source>
        <translation>AJOUT DE L&apos;ID DANS LA TABLE DE METADONNÉES DU CLONE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="447"/>
        <source>Server metadata added in the clone database</source>
        <translation>Les métadonnées ont été ajoutées dans la base clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="451"/>
        <source>Error while adding server id in clone metadata table</source>
        <translation>Erreur lors de l&apos;ajout de l&apos;id dans la table de métadonnées</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="458"/>
        <source>ADDING THE LIST OF SYNCHRONIZED SCHEMAS FOR THIS CLONE IN THE CENTRAL DATABASE </source>
        <translation>AJOUT DE LA LISTE DES SCHÉMAS SYNCHRONISÉS POUR CE CLONE SUR LE SERVEUR CENTRAL</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="476"/>
        <source>List of synchronized schemas added in central database for this clone</source>
        <translation>La liste des schémas synchronisés a été ajoutée sur le serveur central pour ce clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="479"/>
        <source>Error while adding the synchronized schemas in the central database</source>
        <translation>Erreur lors de l&apos;ajout des schémas synchronisés sur la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="484"/>
        <source>ADD CLONE ID IN THE CENTRAL DATABASE HISTORY ITEM FOR THIS ARCHIVE DEPLOYEMENT</source>
        <translation>AJOUT DE L&apos;ID DU CLONE DANS LA TABLE D&apos;HISTORIQUE DU SERVEUR CENTRAL POUR CE CHARGEMENT D&apos;ARCHIVE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="503"/>
        <source>History item has been successfully updated for this archive deployement in the central database</source>
        <translation>L&apos;item d&apos;historique a bien été mis à jour sur la base centrale pour ce chargement d&apos;archive</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="506"/>
        <source>Error while updating the history item for this archive deployement</source>
        <translation>Erreur lors de la mise à jour de l&apos;item d&apos;historique pour ce chargement d&apos;archive</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="511"/>
        <source>The central database ZIP package has been successfully deployed to the clone</source>
        <translation>L&apos;archive ZIP a bien été chargée sur la base clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="53"/>
        <source>Two-way database synchronization between central and clone databases</source>
        <translation>Synchronisation bi-directionnelle entre la base centrale et la base clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="70"/>
        <source>03 Synchronize data and files</source>
        <translation>03 Synchroniser les données et les fichiers</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="148"/>
        <source>Internet connection OK</source>
        <translation>Connexion internet OK</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="173"/>
        <source>Server id</source>
        <translation>Id du serveur</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="191"/>
        <source>Clone id</source>
        <translation>Id du clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="427"/>
        <source>Number of features to synchronize</source>
        <translation>Nombre d&apos;objet à synchroniser</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="342"/>
        <source>SQL queries have been replayed from the central to the clone database</source>
        <translation>Les requêtes SQL ont été rejouées de la base centrale vers la base clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="368"/>
        <source>Logged actions sync_data has been updated in the central database with the clone id</source>
        <translation>Les logs d&apos;actions ont été mis à jour sur la base centrale pour avec cet id de clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="389"/>
        <source>History sync_status has been updated to &quot;done&quot; in the central database</source>
        <translation>L&apos;historique sync_status a été changé en &quot;done&quot; sur la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="395"/>
        <source>No data to synchronize from the central database</source>
        <translation>Aucune donnée à synchroniser depuis la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="462"/>
        <source>New history item has been created in the central database</source>
        <translation>Un nouvel item d&apos;historique a été créé sur la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="527"/>
        <source>Two-way database synchronization done</source>
        <translation>Synchronisation bi-directionnelle réalisée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="65"/>
        <source>Synchronize the clone media subfolder to the central FTP server</source>
        <translation>Synchroniser le répertoire media vers le serveur FTP central</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="107"/>
        <source>Local QGIS project folder</source>
        <translation>Répertoire de projets QGIS local</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="126"/>
        <source>Central FTP Server host</source>
        <translation>Central - Hôte du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="135"/>
        <source>Central FTP Server port</source>
        <translation>Central - Port du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="144"/>
        <source>Central FTP Server login</source>
        <translation>Central - Utilisateur du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="153"/>
        <source>Central FTP Server remote directory</source>
        <translation>Central - Répertoire distant du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="188"/>
        <source>Check internet connection</source>
        <translation>Vérification de la connexion internet</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="240"/>
        <source>Could not retrieve password from ~/.netrc file</source>
        <translation>Le mot de passe n&apos;a pas pu être récupéré du fichier ~/.netrc</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="243"/>
        <source>Could not retrieve password from ~/.netrc file or is empty</source>
        <translation>Le mot de passe n&apos;a pas pu être récupéré du fichier ~/.netrc ou est vide</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="255"/>
        <source>CHECK LOCAL PROJECT DIRECTORY</source>
        <translation>VÉRIFICATION DU RÉPERTOIRE DE PROJETS LOCAL</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="257"/>
        <source>QGIS project local directory not found</source>
        <translation>Le répertoire de projets QGIS local n&apos;a pas été trouvé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="260"/>
        <source>QGIS project local directory ok</source>
        <translation>Le répertoire de projets QGIS local existe bien</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="263"/>
        <source>CHECK REMOTE DIRECTORY</source>
        <translation>VÉRIFICATION DU RÉPERTOIRE DISTANT</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="270"/>
        <source>Remote directory exists in the central server</source>
        <translation>Le répertoire distant existe bien sur le serveur central</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="273"/>
        <source>Remote directory does not exist</source>
        <translation>Le répertoire distant n&apos;existe pas</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="249"/>
        <source>START FTP DIRECTORY SYNCHRONIZATION TO SERVER</source>
        <translation>DÉMARRAGE DE LA SYNCHRONISATION FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="295"/>
        <source>Local directory</source>
        <translation>Répertoire local</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="253"/>
        <source>FTP remote directory</source>
        <translation>Répertoire FTP distant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="262"/>
        <source>Local directory does not exists. No synchronization needed.</source>
        <translation>Le répertoire local n&apos;existe pas. Aucune synchronisation nécessaire.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="267"/>
        <source>Media upload subfolder sucessfully synchronized to the central server</source>
        <translation>Le sous-répertoire upload a bien été synchronisé vers le serveur central</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="58"/>
        <source>Create a package from the central database</source>
        <translation>Créer une archive de données depuis la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="121"/>
        <source>List of schemas to package, separated by commas. (schemas public, lizsync &amp; audit are never processed)</source>
        <translation>Lister les schémas à sauvegarder, séparés par virgule. (Les schémas public, lizsync &amp; audit ne sont jamais traités)</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="137"/>
        <source>Output archive file (ZIP)</source>
        <translation>Archive ZIP exportée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="170"/>
        <source>CHECK IF LIZSYNC HAS BEEN INSTALLED AND DATABASE INITIALIZED</source>
        <translation>VÉRIFICATION DE L&apos;INSTALLATION DE LIZSYNC ET DE L&apos;INITIALISATION DE LA BASE DE DONNÉES</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="177"/>
        <source>Some needed configuration are missing in the central database. Please correct them before proceeding.</source>
        <translation>Certaines configurations nécessaires sont manquantes sur la base centrale. Veuillez les mettre en oeuvre avant de continuer.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="188"/>
        <source>Every test has passed successfully !</source>
        <translation>Tous les tests sont ok !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="268"/>
        <source>CREATE SCRIPT 01_before.sql</source>
        <translation>CRÉATION DU SCRIPT 01_before.sql</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="302"/>
        <source>File 01_before.sql created</source>
        <translation>Fichier 01_before.sql créé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="306"/>
        <source>CREATE SCRIPT 02_data.sql</source>
        <translation>CRÉATION DU SCRIPT 02_data.sql</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="323"/>
        <source>CREATE SCRIPT 03_after.sql</source>
        <translation>CRÉATION DU SCRIPT 03_after.sql</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="348"/>
        <source>File 03_after.sql created</source>
        <translation>Fichier 03_after.sql créé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="353"/>
        <source>CREATE SCRIPT 04_lizsync.sql</source>
        <translation>CRÉATION DU SCRIPT 04_lizsync.sql</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="371"/>
        <source>ADD SCHEMAS TO FILE sync_schemas.txt</source>
        <translation>AJOUT DES SCHÉMAS AU FICHIER sync_schemas.txt</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="380"/>
        <source>File sync_schemas.txt created</source>
        <translation>Fichier sync_schemas.txt créé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="387"/>
        <source>ADD NEW SYNC HISTORY ITEM IN CENTRAL DATABASE</source>
        <translation>AJOUT D&apos;UN NOUVEL ITEM D&apos;HISTORIQUE SUR LA BASE CENTRALE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="415"/>
        <source>New synchronization history item has been added in the central database</source>
        <translation>Le nouvel item d&apos;historique a bien été ajouté sur la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="420"/>
        <source>File sync_id.txt created</source>
        <translation>Fichier sync_id.txt créé</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="429"/>
        <source>No synchronization item could be added !</source>
        <translation>Aucun item d&apos;historique n&apos;a pu être ajouté !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="457"/>
        <source>Error while zipping file</source>
        <translation>Erreur de création du fichier ZIP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="460"/>
        <source>Package has been successfully created !</source>
        <translation>L&apos;archive a bien été créée !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/send_projects_and_files_to_clone_ftp.py" line="68"/>
        <source>Send local QGIS projects and files to the clone FTP server</source>
        <translation>Envoyer les projets QGIS locaux et les fichiers sur le clone via FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="112"/>
        <source>PostgreSQL connection to the local database</source>
        <translation>Connexion PostgreSQL à la base de données clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="194"/>
        <source>Local desktop QGIS project folder</source>
        <translation>Répertoire de projets QGIS local</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="367"/>
        <source>Clone FTP Server host</source>
        <translation>Clone - Hôte du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="231"/>
        <source>Clone FTP Server port</source>
        <translation>Clone - Port du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="376"/>
        <source>Clone FTP Server login</source>
        <translation>Clone - Utilisateur du serveur FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="379"/>
        <source>Clone FTP Server remote directory</source>
        <translation>Clone - Répertoire distant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="162"/>
        <source>List of sub-directory to exclude from synchro, separated by commas.</source>
        <translation>Liste de sous-répertoires à exclure de la synchronisation, séparés par virgule</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="215"/>
        <source>CHECK INTERNET CONNECTION</source>
        <translation>VÉRIFICATION DE LA CONNEXION INTERNET</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="296"/>
        <source>FTP directory</source>
        <translation>Répertoire FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/send_projects_and_files_to_clone_ftp.py" line="302"/>
        <source>Synchronization successfull</source>
        <translation>Synchronisation réussie</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="82"/>
        <source>Cannot connect to database with</source>
        <translation>Impossible de se connecter à la base de données avec</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="90"/>
        <source>Unable to get database from connection</source>
        <translation>Impossible de récupérer la base de données depuis la connexion</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="166"/>
        <source>Cannot connect to database</source>
        <translation>Impossible de se connecter à la base de données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="196"/>
        <source>Unknown error occured while fetching data</source>
        <translation>Une erreur inconnue s&apos;est produire pendant la récupération des données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="272"/>
        <source>Lizsync structure has been installed</source>
        <translation>La structure Lizsync a bien été installée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="284"/>
        <source>The table lizsync.metadata has not been found</source>
        <translation>La table lizsync.metadata n&apos;a pas été trouvée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="295"/>
        <source>Server id is not empty</source>
        <translation>L&apos;id du serveur n&apos;est pas vide</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="304"/>
        <source>The server id in lizsync.metadata is not set</source>
        <translation>L&apos;id du serveur dans la table lizsync.metadata n&apos;est pas défini</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="315"/>
        <source>No missing uid columns</source>
        <translation>Aucun champ uid n&apos;est manquant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="340"/>
        <source>Some tables do not have the required uid column</source>
        <translation>Certaines tables n&apos;ont pas le champ uid requis</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="349"/>
        <source>No missing audit triggers</source>
        <translation>Aucun trigger d&apos;audit n&apos;est manquant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="374"/>
        <source>Some tables are not monitored by the audit trigger tool</source>
        <translation>Certaines tables ne sont pas suivies par le trigger d&apos;audit</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="419"/>
        <source>No FTP binary has been found in your system</source>
        <translation>Aucun exécutable FTP n&apos;a été trouvé sur votre système</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="420"/>
        <source>FTP Binary has been found in your system</source>
        <translation>Les exécutables FTP ont été trouvé sur votre système</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="549"/>
        <source>Error during FTP sync</source>
        <translation>Erreur lors de la synchronisation FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="552"/>
        <source>FTP sync done</source>
        <translation>Synchronisation FTP réalisée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="572"/>
        <source>PostgreSQL pg_dump tool cannot be found in specified path</source>
        <translation>L&apos;outil pg_dump de PostgreSQL n&apos;a pas été trouvé dans le chemin spécifié</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="629"/>
        <source>Database has been successfull dumped</source>
        <translation>La base de données a bien été sauvegardée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="632"/>
        <source>Error dumping database</source>
        <translation>Erreur lors de la sauvegarde de la base de données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="695"/>
        <source>Process QGIS project file</source>
        <translation>Traitement du projet QGIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/tools.py" line="731"/>
        <source>Overwrite QGIS project file with new data</source>
        <translation>Écrasement du projet QGIS avec les nouvelles données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="75"/>
        <source>Configure Lizsync plugin</source>
        <translation>Configurer le plugin Lizsync</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="342"/>
        <source>WinSCP binary path (Windows only)</source>
        <translation>Chemin vers les exécutables WinSCP (pour Windows seulement)</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="132"/>
        <source>PostgreSQL connection to the CENTRAL database</source>
        <translation>Connexion PostgreSQL à la base de données CENTRALE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="357"/>
        <source>Central FTP Server password</source>
        <translation>Central - Mot de passe FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="206"/>
        <source>PostgreSQL connection to the CLONE database</source>
        <translation>Connexion PostgreSQL à la base de données CLONE</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="249"/>
        <source>Clone FTP Server password</source>
        <translation>Clone - Mot de passe FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="172"/>
        <source>Clone QGIS project folder</source>
        <translation>Clone - Répertoire des projets QGIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="388"/>
        <source>Database ZIP archive default path</source>
        <translation>Chemin par défaut de l&apos;archive ZIP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="340"/>
        <source>PostgreSQL local binary path</source>
        <translation>Chemin vers les exécutables PostgreSQL</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="345"/>
        <source>PostgreSQL connection to central database</source>
        <translation>Connexion PostgreSQL à la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="364"/>
        <source>PostgreSQL connection to local clone database</source>
        <translation>Connexion PostgreSQL à la base clone</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="370"/>
        <source>clone FTP Server port</source>
        <translation>Clone - Port FTP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="382"/>
        <source>Local Desktop QGIS project folder</source>
        <translation>Répertoire local des projets QGIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="392"/>
        <source>Configuration has been saved</source>
        <translation>La configuration a été sauvegardée</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="54"/>
        <source>Upgrade LizSync tools in the central database</source>
        <translation>Mettre à jour les outils Lizsync sur la base centrale</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="99"/>
        <source>Check this box to upgrade. No action will be done otherwise</source>
        <translation>Cocher cette case pour lancer la mise à jour. Aucune action ne sera effectuée sinon</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="195"/>
        <source>You must check the box to run the upgrade !</source>
        <translation>Vous devez cocher la case pour lancer la mise à jour !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="216"/>
        <source>No installed version found in the database !</source>
        <translation>Aucune version installée n&apos;a été trouvée dans la base de données !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="219"/>
        <source>Database structure version</source>
        <translation>Version de la structure de la base de données</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="227"/>
        <source>Plugin version</source>
        <translation>Version du plugin</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="233"/>
        <source>The database version already matches the plugin version. No upgrade needed.</source>
        <translation>La version de la structure de la base de données correspond déjà à la version du plugin. Aucune mise à jour n&apos;est nécessaire</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="293"/>
        <source>Lizsync database structure has been successfully upgraded.</source>
        <translation>La structure de la base de données a bien été mise à jour</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="67"/>
        <source>Get projects and files from the central FTP server</source>
        <translation>Récupérer les projets QGIS et les fichiers depuis le serveur central</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="76"/>
        <source> Get QGIS projects and files from the give FTP server and remote directory and adapt QGIS projects for the local clone database by replacing PostgreSQL connection data with the local PostgreSQL server data. An internet connection is needed to use this algorithm</source>
        <translation>Récupère les projets QGIS et les fichiers depuis le répertoire distant du serveur FTP et adapte les projets QGIS au clone en remplaçant les informations de connexion PostgreSQL par celles du clone. Une connexion internet est nécessaire pour utiliser cet algorithme</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="286"/>
        <source>USELAND CONTEXT: Remove old QGIS project files to avoid bug</source>
        <translation>CONTEXTE USERLAND: Supprime les vieux projets QGIS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="309"/>
        <source>ADAPT QGIS PROJECTS FOR OFFLINE USE</source>
        <translation>ADAPTE LES PROJETS QGIS POUR UN USAGE LOCAL</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/get_projects_and_files_from_central_ftp.py" line="316"/>
        <source>QGIS projects and file successfully synchronized from the central FTP server</source>
        <translation>Les projets QGIS et les fichiers ont bien été synchronisés depuis le serveur FTP central</translation>
    </message>
    <message>
        <location filename="../../processing/provider.py" line="67"/>
        <source>Lizsync</source>
        <translation>Lizsync</translation>
    </message>
    <message>
        <location filename="../../test/test_translations.py" line="48"/>
        <source>Good morning</source>
        <translation>Bonjour</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/initialize_central_database.py" line="69"/>
        <source> Prepare the central server PostgreSQL database with the needed data for LizSync tool.

 LizSync needs to have :
 * A server ID stored in the lizsync.server_metadata table
 * All tables from the given schema must have a unique identifier column (uid) with standard uuid inside
 * All tables from the given schema must be audited (trigger of the audit tool)

 You can pass a list of PostgreSQL central database schemas and this alg will add the necessary data and tools</source>
        <translation>Prépare la base de données PostgreSQL du serveur central avec les informations nécessaires pour l&apos;outil LizSync.

LizSync a besoin :
* d&apos;un ID de serveur stocké dans la table lizsync.server_metadata
* Toutes les tables des schémas choisis doivent avoir une colonne d&apos;identifiant unique (uid) contenant un UUID
* Toutes les tables des schémas choisis doivent être suivis par les triggers d&apos;audit)

Vous pouvez fournir une liste de schémas PostgreSQL de la base centrale, cet algorithme ajoutera les éléments nécessaires si besoin</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_database.py" line="62"/>
        <source> This scripts run a two-way data synchronization between the central and clone database.

 The data to synchronize are listed by reading the content of the &quot;audit.logged_actions&quot; of each database, since the last synchronization or the last deployement of ZIP package.

 This audit data are transformed into INSERT/UPDATE/DELETE SQL queries which are played in the databases in this order:
 1/ From the CENTRAL to the CLONE database
 2/ From the CLONE to the CENTRAL database

The central database stores which clone has replayed which audited modification, and keeps an history of synchronization items.</source>
        <translation>Ce script lance une synchronisation bi-directionnelle entre la base de données centrale et le clone.

Les données à synchroniser sont récupérées en lisant le contenu de la table &quot;audit.logged_actions&quot; de chaque base de données, depuis la dernière synchronisation ou le dernier chargement d&apos;une archive ZIP.

Les logs de modification des données sont transformés en commandes SQL INSERT/UPDATE/DELETE qui sont jouées sur les bases de données dans cet ordre:
1/ Depuis le serveur central vers le clone
2/ Depuis le clone vers le serveur central

La base de donnée centrale stocke quels sont les clones qui ont rejoués les logs de modification, et garde un historique des synchronisations.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/synchronize_media_subfolder_to_ftp.py" line="74"/>
        <source> Send media files, such as new images, stored in the clone QGIS &quot;media/upload/&quot; folder, TO the central FTP server remote directory &quot;media/upload/&quot;

 These media files can for example have been added by using Lizmap editing form.

 Every file existing in the clone &quot;media/upload/&quot; folder but not in the central server &quot;media/upload/&quot; folder will be sent.</source>
        <translation>Envoi les fichiers media, comme les nouvelles images, stockées dans le répertoire &quot;media/upload&quot; du répertoire des projets QGIS du clone, VERS le répertoire &quot;media/upload&quot; du serveur FTP central

Ces fichiers media peuvent par exemple avoir été ajouté par les outils d&apos;édition de Lizmap.

Chaque fichier existant sur le clone mais pas sur le serveur sera envoyé.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/package_central_database.py" line="67"/>
        <source> Package data from the central database, for future deployement on one or several clone(s).

 This script backups all data from the given list of schemas to a ZIP archive, named by default &quot;central_database_package.zip&quot;.

 An internet connection is needed because a synchronization item must be written to the central database &quot;lizsync.history&quot; table during the process. and obviously data must be downloaded from the central database</source>
        <translation>Récupère des données depuis la base de données centrale, pour un futur chargement sur un ou plusieurs clone(s).

Ce script sauvegarde toutes les données de la liste de schémas spécifiée vers une archive ZIP, nommée par défaut &quot;central_database_package.zip&quot;.

Une connexion internet est nécessaire pour pouvoir créer un item d&apos;historique de synchronisation sur la base centrale dans la table &quot;lizsync.history&quot;, et naturellement pour pouvoir télécharger les données de la base de données centrale.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/send_projects_and_files_to_clone_ftp.py" line="77"/>
        <source> Send QGIS projects and files to the clone FTP server remote directory.

 This script can be used by the geomatician in charge of the deployment of data to one or several clone(s).

 It synchronizes the files from the given local QGIS project folder to the clone remote folder by using the given FTP connexion. This means all the files from the clone folder will be overwritten by the files from the local QGIS project folder.

 Beware ! This script does not adapt projects for the clone database (no modification of the PostgreSQL connexion data inside the QGIS project files) !</source>
        <translation>Envoie les projets QGIS et les fichiers vers le répertoire distant du serveur FTP du clone.

Ce script peut être utilisé par le géomaticien en charge du déploiement des données vers un ou plusieurs clone(s).

Il synchronise les fichiers depuis le répertoire QGIS local spécifié vers le répertoire distant du clone à travers une connexion FTP. Tous les fichiers existants sur le clone seront écrasés par les versions venant du répertoire de projets QGIS local.

Attention ! Ce script ne fait pas l&apos;adaptation des projets QGIS pour que la connexion se fasse vers la base de données du clone (pas de modification des informations de connexion PostgreSQL dans les fichiers de projet QGIS)!</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/upgrade_database_structure.py" line="63"/>
        <source> Upgrade the Lizsync tables and functions in the central database.

 If you have upgraded your QGIS LizSync plugin, you can run this script to upgrade your central database to the new plugin version.</source>
        <translation>Mise à jour des tables et fonctions Lizsync sur la base de données centrale.

Si vous avez mis à jour votre extension LizSync pour QGIS, vous pouvez utiliser ce script pour mettre à jour votre base de données centrale vers la nouvelle version.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="230"/>
        <source>CHECK UNCOMPRESSED FILES</source>
        <translation>VÉRIFICATION DES FICHIERS DÉCOMPRESSÉS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="241"/>
        <source>One mandatory file has not been found in the ZIP archive</source>
        <translation>Un fichier nécessaire n&apos;a pas été trouvé dans l&apos;archive ZIP</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="243"/>
        <source>All the mandatory files have been sucessfully found</source>
        <translation>Tous les fichiers nécessaires ont bien été trouvés</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="296"/>
        <source>CHECK LAST SYNCHRONIZATION</source>
        <translation>VÉRIFICATION DES DERNIÈRES SYNCHRONISATIONS</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="300"/>
        <source>No synchronization ID has been found in the file sync_id.txt</source>
        <translation>Aucun ID de synchronisation n&apos;a été trouvé dans le fichier sync_id.txt</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="333"/>
        <source>Synchronization has already been made on this clone since the deployment of this package. Abort the current deployment</source>
        <translation>Une ou plusieurs synchronisation ont déjà été réalisées sur ce clone depuis la création de cette archive. On annule le chargement courant</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/create_database_structure.py" line="63"/>
        <source> Install the LizSync schema with tables and function on the central database.

 This script will add
 * An audit schema with auditing functions and tables
 * A lizsync schema with tables and functions

Beware ! If you check the &quot;override&quot; checkboxes, you will loose all existing data in the audit and/or lizsync schema !</source>
        <translation>Installe la structure de Lizsync sur la base de données centrale.

Ce script va ajouter:
* Un schéma audit avec les fonctions et tables d&apos;audit
* Un schéma lizsync avec les tables et fonctions

Attention ! Si vous cochez la case &quot;écraser&quot;, vous perdrez toutes les données existantes dans le schéma audit et/ou le schéma lizsync !</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/deploy_database_server_package.py" line="66"/>
        <source> Deploy a ZIP archive, previously saved with the &quot;Package central database&quot; algorithm, to the chosen clone. This ZIP archive, named by default &quot;central_database_package.zip&quot; contains data from the central PostgreSQL database.</source>
        <translation>Charger une archive ZIP, générée précédemment via l&apos;algorithme &quot;Créer une archive de données depuis la base centrale&quot;, vers le clone choisi. Cette archive ZIP, nommée par défaut &quot;central_database_package&quot;, contient les données sauvegardées depuis la base PostgreSQL centrale.</translation>
    </message>
    <message>
        <location filename="../../processing/algorithms/configure_plugin.py" line="84"/>
        <source> Configure the LizSync plugin

 You must run this script before any other script.
 Every parameter will be used in the other algorithms, as default values for parameters.</source>
        <translation>Configure l&apos;extension Lizsync

Vous devez absolument lancer ce script avant tout autre algorithme.
Chaque valeur sera utilisée dans les autres algorithmes, comme valeur par défaut pour les paramètres correspondants.</translation>
    </message>
</context>
</TS>
